set(_CATKIN_CURRENT_PACKAGE "detection_3d_to_markers")
set(detection_3d_to_markers_VERSION "0.0.0")
set(detection_3d_to_markers_MAINTAINER "rmensing <rmensing@todo.todo>")
set(detection_3d_to_markers_PACKAGE_FORMAT "2")
set(detection_3d_to_markers_BUILD_DEPENDS "vision_msgs" "visualization_msgs" "roscpp")
set(detection_3d_to_markers_BUILD_EXPORT_DEPENDS "vision_msgs" "visualization_msgs" "roscpp")
set(detection_3d_to_markers_BUILDTOOL_DEPENDS "catkin")
set(detection_3d_to_markers_BUILDTOOL_EXPORT_DEPENDS )
set(detection_3d_to_markers_EXEC_DEPENDS "vision_msgs" "visualization_msgs" "roscpp")
set(detection_3d_to_markers_RUN_DEPENDS "vision_msgs" "visualization_msgs" "roscpp")
set(detection_3d_to_markers_TEST_DEPENDS )
set(detection_3d_to_markers_DOC_DEPENDS )
set(detection_3d_to_markers_URL_WEBSITE "")
set(detection_3d_to_markers_URL_BUGTRACKER "")
set(detection_3d_to_markers_URL_REPOSITORY "")
set(detection_3d_to_markers_DEPRECATED "")