set(_CATKIN_CURRENT_PACKAGE "ros_solution")
set(ros_solution_VERSION "0.0.0")
set(ros_solution_MAINTAINER "bchahine <bchahine@todo.todo>")
set(ros_solution_PACKAGE_FORMAT "2")
set(ros_solution_BUILD_DEPENDS "roscpp" "turtlesim" "geometry_msgs" "prius_msgs")
set(ros_solution_BUILD_EXPORT_DEPENDS )
set(ros_solution_BUILDTOOL_DEPENDS "catkin")
set(ros_solution_BUILDTOOL_EXPORT_DEPENDS )
set(ros_solution_EXEC_DEPENDS "roscpp" "turtlesim" "geometry_msgs" "prius_msgs")
set(ros_solution_RUN_DEPENDS "roscpp" "turtlesim" "geometry_msgs" "prius_msgs")
set(ros_solution_TEST_DEPENDS )
set(ros_solution_DOC_DEPENDS )
set(ros_solution_URL_WEBSITE "")
set(ros_solution_URL_BUGTRACKER "")
set(ros_solution_URL_REPOSITORY "")
set(ros_solution_DEPRECATED "")