set(_CATKIN_CURRENT_PACKAGE "car_simulation")
set(car_simulation_VERSION "0.0.1")
set(car_simulation_MAINTAINER "Tully Foote <tfoote@openrobotics.org>")
set(car_simulation_PACKAGE_FORMAT "2")
set(car_simulation_BUILD_DEPENDS "gazebo_ros" "prius_msgs")
set(car_simulation_BUILD_EXPORT_DEPENDS "gazebo_ros" "prius_msgs")
set(car_simulation_BUILDTOOL_DEPENDS "catkin")
set(car_simulation_BUILDTOOL_EXPORT_DEPENDS )
set(car_simulation_EXEC_DEPENDS "fake_localization" "joy" "prius_description" "robot_state_publisher" "rospy" "rviz" "sensor_msgs" "tf2_ros" "gazebo_ros" "prius_msgs")
set(car_simulation_RUN_DEPENDS "fake_localization" "joy" "prius_description" "robot_state_publisher" "rospy" "rviz" "sensor_msgs" "tf2_ros" "gazebo_ros" "prius_msgs")
set(car_simulation_TEST_DEPENDS )
set(car_simulation_DOC_DEPENDS )
set(car_simulation_URL_WEBSITE "")
set(car_simulation_URL_BUGTRACKER "")
set(car_simulation_URL_REPOSITORY "")
set(car_simulation_DEPRECATED "")