set(_CATKIN_CURRENT_PACKAGE "cloud_conversions")
set(cloud_conversions_VERSION "0.0.0")
set(cloud_conversions_MAINTAINER "rmensing <rmensing@todo.todo>")
set(cloud_conversions_PACKAGE_FORMAT "2")
set(cloud_conversions_BUILD_DEPENDS "pcl_ros" "roscpp" "sensor_msgs")
set(cloud_conversions_BUILD_EXPORT_DEPENDS "pcl_ros" "roscpp" "sensor_msgs")
set(cloud_conversions_BUILDTOOL_DEPENDS "catkin")
set(cloud_conversions_BUILDTOOL_EXPORT_DEPENDS )
set(cloud_conversions_EXEC_DEPENDS "pcl_ros" "roscpp" "sensor_msgs")
set(cloud_conversions_RUN_DEPENDS "pcl_ros" "roscpp" "sensor_msgs")
set(cloud_conversions_TEST_DEPENDS )
set(cloud_conversions_DOC_DEPENDS )
set(cloud_conversions_URL_WEBSITE "")
set(cloud_conversions_URL_BUGTRACKER "")
set(cloud_conversions_URL_REPOSITORY "")
set(cloud_conversions_DEPRECATED "")